
package gr.codehub.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CurrencyService", targetNamespace = "http://model.codehub.gr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CurrencyService {


    /**
     * 
     * @param arg0
     * @return
     *     returns gr.codehub.client.Currency
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.SaveResponse")
    @Action(input = "http://model.codehub.gr/CurrencyService/saveRequest", output = "http://model.codehub.gr/CurrencyService/saveResponse")
    public Currency save(
        @WebParam(name = "arg0", targetNamespace = "")
        Currency arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCurrencies", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.GetAllCurrencies")
    @ResponseWrapper(localName = "getAllCurrenciesResponse", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.GetAllCurrenciesResponse")
    @Action(input = "http://model.codehub.gr/CurrencyService/getAllCurrenciesRequest", output = "http://model.codehub.gr/CurrencyService/getAllCurrenciesResponse")
    public List<Object> getAllCurrencies();

    /**
     * 
     * @param arg0
     * @return
     *     returns gr.codehub.client.Currency
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByCode", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.FindByCode")
    @ResponseWrapper(localName = "findByCodeResponse", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.FindByCodeResponse")
    @Action(input = "http://model.codehub.gr/CurrencyService/findByCodeRequest", output = "http://model.codehub.gr/CurrencyService/findByCodeResponse")
    public Currency findByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns gr.codehub.client.Currency
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteById", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.DeleteById")
    @ResponseWrapper(localName = "deleteByIdResponse", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.DeleteByIdResponse")
    @Action(input = "http://model.codehub.gr/CurrencyService/deleteByIdRequest", output = "http://model.codehub.gr/CurrencyService/deleteByIdResponse")
    public Currency deleteById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns gr.codehub.client.Currency
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrencyById", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.GetCurrencyById")
    @ResponseWrapper(localName = "getCurrencyByIdResponse", targetNamespace = "http://model.codehub.gr/", className = "gr.codehub.client.GetCurrencyByIdResponse")
    @Action(input = "http://model.codehub.gr/CurrencyService/getCurrencyByIdRequest", output = "http://model.codehub.gr/CurrencyService/getCurrencyByIdResponse")
    public Currency getCurrencyById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
